name: youtube_clone_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # *YOUTUBE_CLONE_APP*
  flutter_config: ^2.0.0
  velocity_x:
  shared_preferences: ^2.0.18
  web_socket_channel: ^2.3.0
  dio:
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato.ttf